// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

#ifndef WINRT_HL2UnityPlugin_1_H
#define WINRT_HL2UnityPlugin_1_H
#include "winrt/impl/HL2UnityPlugin.0.h"
WINRT_EXPORT namespace winrt::HL2UnityPlugin
{
    struct __declspec(empty_bases) IHL2ResearchMode :
        Windows::Foundation::IInspectable,
        impl::consume_t<IHL2ResearchMode>
    {
        IHL2ResearchMode(std::nullptr_t = nullptr) noexcept {}
        IHL2ResearchMode(void* ptr, take_ownership_from_abi_t) noexcept : Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
