// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

#ifndef WINRT_HL2UnityPlugin_2_H
#define WINRT_HL2UnityPlugin_2_H
#include "winrt/impl/HL2UnityPlugin.1.h"
WINRT_EXPORT namespace winrt::HL2UnityPlugin
{
    struct __declspec(empty_bases) HL2ResearchMode : HL2UnityPlugin::IHL2ResearchMode
    {
        HL2ResearchMode(std::nullptr_t) noexcept {}
        HL2ResearchMode(void* ptr, take_ownership_from_abi_t) noexcept : HL2UnityPlugin::IHL2ResearchMode(ptr, take_ownership_from_abi) {}
        HL2ResearchMode();
    };
}
#endif
