// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.200729.8

void* winrt_make_HL2UnityPlugin_HL2ResearchMode()
{
    return winrt::detach_abi(winrt::make<winrt::HL2UnityPlugin::factory_implementation::HL2ResearchMode>());
}
WINRT_EXPORT namespace winrt::HL2UnityPlugin
{
    HL2ResearchMode::HL2ResearchMode() :
        HL2ResearchMode(make<HL2UnityPlugin::implementation::HL2ResearchMode>())
    {
    }
}
